version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /packaging/docker
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
